### ISSUE TITLE
场景中光照闪烁

### ISSUE THREAD

**Issue by Taoist-Yu** [xuechao-chen/DDGI#1]
随着光源运动时，墙壁上接收到的光照会有闪烁，请问一下这种是属于正常现象还是artifact？

**Comment by xuechao-chen** [comment]
属于DDGI这个方法本身的artifact...因为每个探针的采样光线数比较少，所以会出现闪烁现象。
________________________________
发件人: 宇道人 ***@***.***>
发送时间: 2021年7月6日 14:51
收件人: xuechao-chen/DDGI ***@***.***>
抄送: Subscribed ***@***.***>
主题: [xuechao-chen/DDGI] 场景中光照闪烁 (#1)


随着光源运动时，墙壁上接收到的光照会有闪烁，请问一下这种是属于正常现象还是artifact？

―
